# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube',
            field=models.SlugField(max_length=100),
        ),
    ]
