# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20161207_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='process_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
