# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='process_status',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
