# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20161207_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='TITLE NOT AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='process_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
