# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20161208_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='PROCESSING . . .', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='process_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'NOT STARTED'), (2, 'PROCESSING'), (3, 'INVALID YOUTUBE ID'), (4, 'DOWNLOAD ERROR'), (5, 'BEAT PROCESS ERROR')], default=1),
        ),
    ]
