version: '2'
services:

  db:
    env_file:
      - db.env
    build: ./data
    hostname: db
    container_name: db01

  rabbit:
    env_file:
      - rabbit.env
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: rq01
    ports:
      - "5672:5672"   # we forward this port because it's useful for debugging
      - "15672:15672" # rabbitmq management plugin

  app:
    restart: always
    env_file:
      - app.env
      - db.env
      - rabbit.env
    build: .
    privileged: true
    hostname: app
    container_name: ap01
    command: ./start_app.sh
    volumes:
      - ./fivefrets/src:/src
      - ./fivefrets/static:/static
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
    depends_on:
      - db

  # Celery worker
  worker:
    restart: always
    env_file:
      - app.env
      - db.env
      - rabbit.env
    build: .
    hostname: worker
    container_name: wk01
    command: ./start_celery.sh
    volumes:
      - ./fivefrets/src:/src
    links:
      - db
      - rabbit
    depends_on:
      - rabbit

  nginx:
    restart: always
    image: nginx:latest
    hostname: nginx
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./fivefrets/src:/src
      - ./nginx:/etc/nginx/conf.d
      - ./fivefrets/static:/static
    depends_on:
      - app
