# APP BUILD

FROM ubuntu:16.04

apt-get update
apt-get install python3
apt-get install python3-tk
apt-get install python3-pip
pip3 install --upgrade pip
apt-get install python3-audioread
pip3 install django
pip3 install numpy
pip3 innstall librosa
