# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'A'), ('2', 'A#'), ('3', 'B'), ('4', 'C'), ('5', 'C#'), ('6', 'D'), ('7', 'D#'), ('8', 'E'), ('9', 'F'), ('10', 'F#'), ('11', 'G'), ('12', 'G#'), ('N', 'X')], max_length=2)),
                ('typ', models.CharField(choices=[('MAJ', 'Major'), ('MIN', 'Minor')], max_length=5)),
                ('alt_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
