# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'A'), ('2', 'A#'), ('3', 'B'), ('4', 'C'), ('5', 'C#'), ('6', 'D'), ('7', 'D#'), ('8', 'E'), ('9', 'F'), ('10', 'F#'), ('11', 'G'), ('12', 'G#'), ('N', 'X')], max_length=2)),
                ('typ', models.CharField(choices=[('MAJ', 'Major'), ('MIN', 'Minor')], max_length=5)),
                ('alt_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GuitarChord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('fret', models.CharField(default=0, max_length=2)),
                ('barre', models.CharField(default=0, max_length=2)),
                ('string6', models.CharField(default=0, max_length=2)),
                ('string5', models.CharField(default=0, max_length=2)),
                ('string4', models.CharField(default=0, max_length=2)),
                ('string3', models.CharField(default=0, max_length=2)),
                ('string2', models.CharField(default=0, max_length=2)),
                ('string1', models.CharField(default=0, max_length=2)),
                ('chord', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chords.Chord')),
            ],
        ),
    ]
