# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarChord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('fret', models.CharField(default=0, max_length=2)),
                ('barre', models.CharField(default=0, max_length=2)),
                ('string6', models.CharField(default=0, max_length=2)),
                ('string5', models.CharField(default=0, max_length=2)),
                ('string4', models.CharField(default=0, max_length=2)),
                ('string3', models.CharField(default=0, max_length=2)),
                ('string2', models.CharField(default=0, max_length=2)),
                ('string1', models.CharField(default=0, max_length=2)),
                ('chord', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chords.Chord')),
            ],
        ),
    ]
