# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarChord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'A'), ('2', 'A#'), ('3', 'B'), ('4', 'C'), ('5', 'C#'), ('6', 'D'), ('7', 'D#'), ('8', 'E'), ('9', 'F'), ('10', 'F#'), ('11', 'G'), ('12', 'G#')], max_length=2)),
                ('alt_name', models.CharField(max_length=10)),
                ('primary', models.BooleanField()),
                ('typ', models.CharField(choices=[('MAJ', 'Major'), ('MIN', 'Minor')], max_length=5)),
                ('barre', models.IntegerField()),
                ('fret', models.IntegerField()),
                ('string1', models.IntegerField()),
                ('string2', models.IntegerField()),
                ('string3', models.IntegerField()),
                ('string4', models.IntegerField()),
                ('string5', models.IntegerField()),
                ('string6', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=50)),
                ('lyric', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SongChord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('chord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chords.GuitarChord')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chords.Song')),
            ],
        ),
        migrations.DeleteModel(
            name='Lyric',
        ),
    ]
