# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0003_auto_20161021_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(to='chords.Singer'),
        ),
    ]
