# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0004_auto_20161021_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='singers',
        ),
    ]
