# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0005_auto_20161021_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='chord',
            name='alt_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.TextField(blank=True),
        ),
    ]
