# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0007_auto_20161022_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songchord',
            name='end',
        ),
        migrations.RemoveField(
            model_name='songchord',
            name='position',
        ),
        migrations.RemoveField(
            model_name='songchord',
            name='start',
        ),
        migrations.AddField(
            model_name='songchord',
            name='beat_position',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='songchord',
            name='modified_chord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_chord', to='chords.Chord'),
        ),
        migrations.AddField(
            model_name='songchord',
            name='start_time',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chords.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chords.Composer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(blank=True, to='chords.Singer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube',
            field=models.CharField(max_length=100),
        ),
    ]
