version: '2'
services:

  db:
    env_file:
      - db.env
    build:
      context: ./data
      dockerfile: Dockerfile
    hostname: db
    container_name: db01

  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    container_name: rmq01
    env_file:
      - rabbit.env
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  app:
    env_file:
      - app.env
      - db.env
      - rabbit.env
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    hostname: app
    container_name: ap01
    command: ./start_app.sh
    volumes:
      - ./src:/src
      - ./static:/static
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
    depends_on:
      - db

  # Celery worker
  worker:
    env_file:
      - app.env
      - db.env
      - rabbit.env
    build:
      context: .
      dockerfile: Dockerfile
    hostname: worker
    container_name: wk01
    command: ./start_celery.sh
    volumes:
      - ./src:/src
    links:
      - db
      - rabbit
    depends_on:
      - rabbit
